### ISSUE TITLE
Allow template engine pages (pug, handlebars.. ) for error pages

### ISSUE THREAD

**Issue by rwambacq** [KNowledgeOnWebScale/walder#49]
Right now, the pages loaded from `x-walder-errors` can only be html files, putting a pug file for any of the error code pages doesn't work.

**Comment by mvanbrab** [comment]
Is this restricted to `x-walder-errors` or could it also be applicable to individual routes?
```
  /whatever/route/{par}:
      ...
      responses:
        200:
          description: list of movies
          x-walder-input-text/html: movies.pug
       400:
          description: specific page not found error
          x-walder-input-text/html: error400forThisRoute.pug
x-walder-errors:
  404:
    description: page not found error
    x-walder-input-text/html: error404default.pug
  500:
    description: internal server error
    x-walder-input-text/html: error500.html
```

Where would the data to be expanded in the template come from in case of errors? Handlers' data won't be available in case of errors and in case of default error pages, the expected fields in the data are not known.

**Comment by pheyvaer** [comment]
Also for individual routes, but normally that should already work.

Templates are not only for errors. For example, they allow you also to defines layouts and so on so that you can reuse certain parts of the code.

**Comment by mvanbrab** [comment]
I tried with following alternative section `x-walder-errors` in modified file `example/config-errors.yaml`, without any changes to the code.
All alternatives (tested one at a time) work, provided of course the referenced files are provided as well.
```
x-walder-errors:
  404:
    description: page not found error
#    x-walder-input-text/html: error404.html
#    x-walder-input-text/html: error404alt.pug
#    x-walder-input-text/html: error404alt.handlebars
    x-walder-input-text/html: error404alt.md
  500:
    description: internal server error
#    x-walder-input-text/html: error500.html
#    x-walder-input-text/html: error500alt.pug
#    x-walder-input-text/html: error500alt.handlebars
    x-walder-input-text/html: error500alt.md
```
How to check:
- check out branch `fix/49`
- run `yarn start -c example/config-errors.yaml`
- visit http://localhost:3000/thisPageSurelyWontExist, http://localhost:3000/bad_pipeModule

Could this issue be a false alert or was it fixed silently in the mean time?
